CREATE SCHEMA [map]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT DELETE ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT EXECUTE ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT INSERT ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT SELECT ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT UPDATE ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [map] TO [BSUH\GRP-L-S-Cancer-SQLAdmins]
GO
GRANT ALTER ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT DELETE ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT EXECUTE ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT INSERT ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT SELECT ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT UPDATE ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [map] TO [SUSSEX\NevilleS001]
GO
