SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [LocalConfig].[tblMAIN_CARE_PLAN] AS

/******************************************************** © Copyright & Licensing ****************************************************************
© 2019 Perspicacity Ltd & Brighton & Sussex University Hospitals

This code / file is part of Perspicacity & BSUH's Cancer Data Warehouse & Reporting suite.

This Cancer Data Warehouse & Reporting suite is free software: you can 
redistribute it and/or modify it under the terms of the GNU Affero 
General Public License as published by the Free Software Foundation, 
either version 3 of the License, or (at your option) any later version.

This Cancer Data Warehouse & Reporting suite is distributed in the hope 
that it will be useful, but WITHOUT ANY WARRANTY; without even the 
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

A full copy of this code can be found at https://github.com/BrightonSussexUniHospitals/CancerReportingSuite

You may also be interested in the other repositories at https://github.com/perspicacity-ltd or
https://github.com/BrightonSussexUniHospitals

Original Work Created Date:	30/07/2020
Original Work Created By:	Perspicacity Ltd (Matthew Bishop) & BSUH (Lawrence Simpson)
Original Work Contact:		07545 878906
Original Work Contact:		matthew.bishop@perspicacityltd.co.uk / lawrencesimpson@nhs.net
Description:				Create a local config view to point at the place where the SCR
							replicated data is located so that the core procedures don't
							need to be changed when they are copied to different environments 
							(e.g. live vs test or from one trust to another)
**************************************************************************************************************************************************/

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(1 AS tinyint) AS SrcSysID
			,PLAN_ID
			,CARE_ID
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,N5_1_MDT_MEETING_YN = N5_1_MDT_MEETING_YN COLLATE DATABASE_DEFAULT
			,N5_2_MDT_DATE
			,N5_3_PLAN_AGREE_DATE
			,N1_3_ORG_CODE_DECISION = N1_3_ORG_CODE_DECISION COLLATE DATABASE_DEFAULT
			,N5_5_CARE_INTENT = N5_5_CARE_INTENT COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_1 = N5_6_TREATMENT_TYPE_1 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_2 = N5_6_TREATMENT_TYPE_2 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_3 = N5_6_TREATMENT_TYPE_3 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_4 = N5_6_TREATMENT_TYPE_4 COLLATE DATABASE_DEFAULT
			,N5_8_NO_TREATMENT = N5_8_NO_TREATMENT COLLATE DATABASE_DEFAULT
			,N5_9_CO_MORBIDITY
			,N5_10_WHO_STATUS
			,N_HN20_PC_DATE
			,N_L19_PCI = N_L19_PCI COLLATE DATABASE_DEFAULT
			,N_L28_PLAN_TYPE = N_L28_PLAN_TYPE COLLATE DATABASE_DEFAULT
			,N_L32_CHOICE = N_L32_CHOICE COLLATE DATABASE_DEFAULT
			,L_LOCATION = L_LOCATION COLLATE DATABASE_DEFAULT
			,L_PRE_POST_OP = L_PRE_POST_OP COLLATE DATABASE_DEFAULT
			,L_ONCOLOGIST = L_ONCOLOGIST COLLATE DATABASE_DEFAULT
			,L_MDT_ACTION_BY = L_MDT_ACTION_BY COLLATE DATABASE_DEFAULT
			,L_PATH_REVIEW = L_PATH_REVIEW COLLATE DATABASE_DEFAULT
			,L_REVIEW_WHO = L_REVIEW_WHO COLLATE DATABASE_DEFAULT
			,L_REFERRED_TO = L_REFERRED_TO COLLATE DATABASE_DEFAULT
			,L_WHO_REFERRED_TO = L_WHO_REFERRED_TO COLLATE DATABASE_DEFAULT
			,L_LETTER_CC = L_LETTER_CC COLLATE DATABASE_DEFAULT
			,L_OTHER_TRUST = L_OTHER_TRUST COLLATE DATABASE_DEFAULT
			,L_TERTIARY_REASON
			,L_NETWORK = L_NETWORK COLLATE DATABASE_DEFAULT
			,L_DATE_NETWORK_MEETING
			,L_NETWORK_ACTIONED = L_NETWORK_ACTIONED COLLATE DATABASE_DEFAULT
			,L_PLANNED_TRANSPLANT
			,R_TYPE_REC = R_TYPE_REC COLLATE DATABASE_DEFAULT
			,R_DIAG_BY = R_DIAG_BY COLLATE DATABASE_DEFAULT
			,R_NOT_CUR = R_NOT_CUR COLLATE DATABASE_DEFAULT
			,L_SEIZURES
			,L_SURGERY
			,L_CARE_PLAN_AGREED = L_CARE_PLAN_AGREED COLLATE DATABASE_DEFAULT
			,L_MDT_SITE = L_MDT_SITE COLLATE DATABASE_DEFAULT
			,L_RESECTIVE_PATHOLOGY
			,L_MDT_COMMENTS = L_MDT_COMMENTS COLLATE DATABASE_DEFAULT
			,L_NETWORK_FEEDBACK = L_NETWORK_FEEDBACK COLLATE DATABASE_DEFAULT
			,L_NETWORK_COMMENTS = L_NETWORK_COMMENTS COLLATE DATABASE_DEFAULT
			,L_REASON_NOT_DISCUSSED
			,R_NOT_DISCUSSED_COMMENTS = R_NOT_DISCUSSED_COMMENTS COLLATE DATABASE_DEFAULT
			,LANSKY_ID
			,ROOT_CAUSE_COMMENTS = ROOT_CAUSE_COMMENTS COLLATE DATABASE_DEFAULT
			,ASA_PROSTATE
			,MULTIPARA_MRI_PERF
			,SPECIALIST_REF_APPTS
			,PLANNED_PROS_TREAT_1 = PLANNED_PROS_TREAT_1 COLLATE DATABASE_DEFAULT
			,PLANNED_PROS_TREAT_2 = PLANNED_PROS_TREAT_2 COLLATE DATABASE_DEFAULT
			,PLANNED_RADIO_INTENT
			,PLANNED_RADIO_TYPE
			,PLANNED_IMAGE_GUIDANCE
			,PLANNED_RADIO_FIELD
			,PLANNED_BRACHY_TYPE
			,PLANNED_BRACHY_TOTAL_DOSE
			,PLANNED_BRACHY_TOTAL_FRACTIONS
			,PLANNED_DUR_NEOADJ_AND_DEP_THERAPY
			,PLANNED_TOT_DUR_ADJ_ANDR_DEPR
			,TERTIARY_REFERRAL_ID
			,COSDMeetingTypeID
			,COSDMeetingTypeComments = COSDMeetingTypeComments COLLATE DATABASE_DEFAULT
			,NPCA_PLAN_AGREED_WITH_PAT
			,NEW_TERTIARY_REFERRAL_ID
			,ACTION_ID
			,COSDMeetingOrg1 = COSDMeetingOrg1 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg2 = COSDMeetingOrg2 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg3 = COSDMeetingOrg3 COLLATE DATABASE_DEFAULT
			,REASON_PAT_DECLINED
			,REASON_UNFIT_PERFORMANCE
			,REASON_UNFIT_COMORBIDITY
			,REASON_UNFIT_ADVANCED
			,REASON_UNKNOWN_PRIMARY
			,REASON_DIED
			,REASON_NO_TREATMENT
			,REASON_OTHER
			,REASON_MONITORING
			,REASON_NOT_KNOWN
			,COSDMeetingOrg4 = COSDMeetingOrg4 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg5 = COSDMeetingOrg5 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg6 = COSDMeetingOrg6 COLLATE DATABASE_DEFAULT
			,CON_RES_DENTIST_ASKED_MDT
			,DENTAL_ASSESS_NECESSARY
			,TertiaryReferralKey
			,MDTDiscussionType
	FROM  [CancerRegister_WSHT]..tblMAIN_CARE_PLAN

		UNION ALL 

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(2 AS tinyint) AS SrcSysID
			,PLAN_ID
			,CARE_ID
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,N5_1_MDT_MEETING_YN = N5_1_MDT_MEETING_YN COLLATE DATABASE_DEFAULT
			,N5_2_MDT_DATE
			,N5_3_PLAN_AGREE_DATE
			,N1_3_ORG_CODE_DECISION = N1_3_ORG_CODE_DECISION COLLATE DATABASE_DEFAULT
			,N5_5_CARE_INTENT = N5_5_CARE_INTENT COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_1 = N5_6_TREATMENT_TYPE_1 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_2 = N5_6_TREATMENT_TYPE_2 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_3 = N5_6_TREATMENT_TYPE_3 COLLATE DATABASE_DEFAULT
			,N5_6_TREATMENT_TYPE_4 = N5_6_TREATMENT_TYPE_4 COLLATE DATABASE_DEFAULT
			,N5_8_NO_TREATMENT = N5_8_NO_TREATMENT COLLATE DATABASE_DEFAULT
			,N5_9_CO_MORBIDITY
			,N5_10_WHO_STATUS
			,N_HN20_PC_DATE
			,N_L19_PCI = N_L19_PCI COLLATE DATABASE_DEFAULT
			,N_L28_PLAN_TYPE = N_L28_PLAN_TYPE COLLATE DATABASE_DEFAULT
			,N_L32_CHOICE = N_L32_CHOICE COLLATE DATABASE_DEFAULT
			,L_LOCATION = L_LOCATION COLLATE DATABASE_DEFAULT
			,L_PRE_POST_OP = L_PRE_POST_OP COLLATE DATABASE_DEFAULT
			,L_ONCOLOGIST = L_ONCOLOGIST COLLATE DATABASE_DEFAULT
			,L_MDT_ACTION_BY = L_MDT_ACTION_BY COLLATE DATABASE_DEFAULT
			,L_PATH_REVIEW = L_PATH_REVIEW COLLATE DATABASE_DEFAULT
			,L_REVIEW_WHO = L_REVIEW_WHO COLLATE DATABASE_DEFAULT
			,L_REFERRED_TO = L_REFERRED_TO COLLATE DATABASE_DEFAULT
			,L_WHO_REFERRED_TO = L_WHO_REFERRED_TO COLLATE DATABASE_DEFAULT
			,L_LETTER_CC = L_LETTER_CC COLLATE DATABASE_DEFAULT
			,L_OTHER_TRUST = L_OTHER_TRUST COLLATE DATABASE_DEFAULT
			,L_TERTIARY_REASON
			,L_NETWORK = L_NETWORK COLLATE DATABASE_DEFAULT
			,L_DATE_NETWORK_MEETING
			,L_NETWORK_ACTIONED = L_NETWORK_ACTIONED COLLATE DATABASE_DEFAULT
			,L_PLANNED_TRANSPLANT
			,R_TYPE_REC = R_TYPE_REC COLLATE DATABASE_DEFAULT
			,R_DIAG_BY = R_DIAG_BY COLLATE DATABASE_DEFAULT
			,R_NOT_CUR = R_NOT_CUR COLLATE DATABASE_DEFAULT
			,L_SEIZURES
			,L_SURGERY
			,L_CARE_PLAN_AGREED = L_CARE_PLAN_AGREED COLLATE DATABASE_DEFAULT
			,L_MDT_SITE = L_MDT_SITE COLLATE DATABASE_DEFAULT
			,L_RESECTIVE_PATHOLOGY
			,L_MDT_COMMENTS = L_MDT_COMMENTS COLLATE DATABASE_DEFAULT
			,L_NETWORK_FEEDBACK = L_NETWORK_FEEDBACK COLLATE DATABASE_DEFAULT
			,L_NETWORK_COMMENTS = L_NETWORK_COMMENTS COLLATE DATABASE_DEFAULT
			,L_REASON_NOT_DISCUSSED
			,R_NOT_DISCUSSED_COMMENTS = R_NOT_DISCUSSED_COMMENTS COLLATE DATABASE_DEFAULT
			,LANSKY_ID
			,ROOT_CAUSE_COMMENTS = ROOT_CAUSE_COMMENTS COLLATE DATABASE_DEFAULT
			,ASA_PROSTATE
			,MULTIPARA_MRI_PERF
			,SPECIALIST_REF_APPTS
			,PLANNED_PROS_TREAT_1 = PLANNED_PROS_TREAT_1 COLLATE DATABASE_DEFAULT
			,PLANNED_PROS_TREAT_2 = PLANNED_PROS_TREAT_2 COLLATE DATABASE_DEFAULT
			,PLANNED_RADIO_INTENT
			,PLANNED_RADIO_TYPE
			,PLANNED_IMAGE_GUIDANCE
			,PLANNED_RADIO_FIELD
			,PLANNED_BRACHY_TYPE
			,PLANNED_BRACHY_TOTAL_DOSE
			,PLANNED_BRACHY_TOTAL_FRACTIONS
			,PLANNED_DUR_NEOADJ_AND_DEP_THERAPY
			,PLANNED_TOT_DUR_ADJ_ANDR_DEPR
			,TERTIARY_REFERRAL_ID
			,COSDMeetingTypeID
			,COSDMeetingTypeComments = COSDMeetingTypeComments COLLATE DATABASE_DEFAULT
			,NPCA_PLAN_AGREED_WITH_PAT
			,NEW_TERTIARY_REFERRAL_ID
			,ACTION_ID
			,COSDMeetingOrg1 = COSDMeetingOrg1 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg2 = COSDMeetingOrg2 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg3 = COSDMeetingOrg3 COLLATE DATABASE_DEFAULT
			,REASON_PAT_DECLINED
			,REASON_UNFIT_PERFORMANCE
			,REASON_UNFIT_COMORBIDITY
			,REASON_UNFIT_ADVANCED
			,REASON_UNKNOWN_PRIMARY
			,REASON_DIED
			,REASON_NO_TREATMENT
			,REASON_OTHER
			,REASON_MONITORING
			,REASON_NOT_KNOWN
			,COSDMeetingOrg4 = COSDMeetingOrg4 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg5 = COSDMeetingOrg5 COLLATE DATABASE_DEFAULT
			,COSDMeetingOrg6 = COSDMeetingOrg6 COLLATE DATABASE_DEFAULT
			,CON_RES_DENTIST_ASKED_MDT
			,DENTAL_ASSESS_NECESSARY
			,TertiaryReferralKey
			,MDTDiscussionType
	FROM  [CancerRegister_BSUH]..tblMAIN_CARE_PLAN
GO
