SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [LocalConfig].[tblMAIN_SURGERY] AS

/******************************************************** © Copyright & Licensing ****************************************************************
© 2019 Perspicacity Ltd & Brighton & Sussex University Hospitals

This code / file is part of Perspicacity & BSUH's Cancer Data Warehouse & Reporting suite.

This Cancer Data Warehouse & Reporting suite is free software: you can 
redistribute it and/or modify it under the terms of the GNU Affero 
General Public License as published by the Free Software Foundation, 
either version 3 of the License, or (at your option) any later version.

This Cancer Data Warehouse & Reporting suite is distributed in the hope 
that it will be useful, but WITHOUT ANY WARRANTY; without even the 
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

A full copy of this code can be found at https://github.com/BrightonSussexUniHospitals/CancerReportingSuite

You may also be interested in the other repositories at https://github.com/perspicacity-ltd or
https://github.com/BrightonSussexUniHospitals

Original Work Created Date:	30/07/2020
Original Work Created By:	Perspicacity Ltd (Matthew Bishop) & BSUH (Lawrence Simpson)
Original Work Contact:		07545 878906
Original Work Contact:		matthew.bishop@perspicacityltd.co.uk / lawrencesimpson@nhs.net
Description:				Create a local config view to point at the place where the SCR
							replicated data is located so that the core procedures don't
							need to be changed when they are copied to different environments 
							(e.g. live vs test or from one trust to another)
**************************************************************************************************************************************************/

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(1 AS tinyint) AS SrcSysID
			,SURGERY_ID
			,CARE_ID
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,N7_1_SITE_CODE = N7_1_SITE_CODE COLLATE DATABASE_DEFAULT
			,N_SITE_CODE_DTT = N_SITE_CODE_DTT COLLATE DATABASE_DEFAULT
			,N7_2_CONSULTANT = N7_2_CONSULTANT COLLATE DATABASE_DEFAULT
			,N7_3_SPECIALTY
			,N7_4_TREATMENT_INTENT
			,N7_5_DECISION_DATE
			,N7_8_ADMISSION_DATE
			,N7_9_SURGERY_DATE
			,L_PROCEDURE_SITE
			,L_PROCEDURE_TYPE
			,L_PROCEDURE
			,L_PROCEDURE_SITE2
			,L_PROCEDURE_TYPE2
			,L_PROCEDURE2
			,L_PROCEDURE_SITE3
			,L_PROCEDURE_TYPE3
			,L_PROCEDURE3
			,L_PROCEDURE_SITE4
			,L_PROCEDURE_TYPE4
			,L_PROCEDURE4
			,N7_10_PROCEDURE_1 = N7_10_PROCEDURE_1 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_2 = N7_11_PROCEDURE_2 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_3 = N7_11_PROCEDURE_3 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_4 = N7_11_PROCEDURE_4 COLLATE DATABASE_DEFAULT
			,N7_12_DISCHARGE_DATE
			,N7_13_DISCHARGE_DESTINATION
			,N_TREATMENT_EVENT = N_TREATMENT_EVENT COLLATE DATABASE_DEFAULT
			,N_TREATMENT_SETTING = N_TREATMENT_SETTING COLLATE DATABASE_DEFAULT
			,L_TRIAL
			,L_SURGEON = L_SURGEON COLLATE DATABASE_DEFAULT
			,L_SURGEON_NAME = L_SURGEON_NAME COLLATE DATABASE_DEFAULT
			,L_GRADE = L_GRADE COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_1 = L_ASSISTANT_1 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_NAME_1 = L_ASSISTANT_NAME_1 COLLATE DATABASE_DEFAULT
			,L_GRADE_1 = L_GRADE_1 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_2 = L_ASSISTANT_2 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_NAME_2 = L_ASSISTANT_NAME_2 COLLATE DATABASE_DEFAULT
			,L_GRADE_2 = L_GRADE_2 COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_NAME = L_ANAESTHETIST_NAME COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST = L_ANAESTHETIST COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_NAME_2 = L_ANAESTHETIST_NAME_2 COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_2 = L_ANAESTHETIST_2 COLLATE DATABASE_DEFAULT
			,L_URGENCY = L_URGENCY COLLATE DATABASE_DEFAULT
			,L_ANASTOMOSIS = L_ANASTOMOSIS COLLATE DATABASE_DEFAULT
			,L_BLOOD_LOSS
			,L_SUPPORT = L_SUPPORT COLLATE DATABASE_DEFAULT
			,L_COMPLICATIONS
			,L_COMPLICATIONS2
			,L_COMPLICATIONS3
			,L_OTHER_COMP = L_OTHER_COMP COLLATE DATABASE_DEFAULT
			,L_POST_COMP = L_POST_COMP COLLATE DATABASE_DEFAULT
			,L_TRANSFER = L_TRANSFER COLLATE DATABASE_DEFAULT
			,L_DAYS
			,L_RETURN_ITU = L_RETURN_ITU COLLATE DATABASE_DEFAULT
			,L_REASON_RETURN = L_REASON_RETURN COLLATE DATABASE_DEFAULT
			,L_DAYS_BACK
			,DEFINITIVE_TREATMENT
			,CWT_PROFORMA
			,L_DISCHARGE_COMMENTS = L_DISCHARGE_COMMENTS COLLATE DATABASE_DEFAULT
			,STEM_CELL_INFUSION_SOURCE_ID
			,STEM_CELL_INFUSION_SOURCE_ID2
			,STEM_CELL_INFUSION_SOURCE_ID3
			,STEM_CELL_INFUSION_DONOR_ID
			,STEM_CELL_INFUSION_DONOR_ID2
			,STEM_CELL_INFUSION_DONOR_ID3
			,SURGEON_3 = SURGEON_3 COLLATE DATABASE_DEFAULT
			,SURGEON_3_GRADE = SURGEON_3_GRADE COLLATE DATABASE_DEFAULT
			,SURGEON_3_NAME = SURGEON_3_NAME COLLATE DATABASE_DEFAULT
			,SURGEON_4 = SURGEON_4 COLLATE DATABASE_DEFAULT
			,SURGEON_4_GRADE = SURGEON_4_GRADE COLLATE DATABASE_DEFAULT
			,SURGEON_4_NAME = SURGEON_4_NAME COLLATE DATABASE_DEFAULT
			,ROOT_ADMISSION_DATE_COMMENTS = ROOT_ADMISSION_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,ROOT_PERFORMED_DATE_COMMENTS = ROOT_PERFORMED_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,GMC_CODE1 = GMC_CODE1 COLLATE DATABASE_DEFAULT
			,GMC_CODE2 = GMC_CODE2 COLLATE DATABASE_DEFAULT
			,GMC_CODE3 = GMC_CODE3 COLLATE DATABASE_DEFAULT
			,GMC_CODE4 = GMC_CODE4 COLLATE DATABASE_DEFAULT
			,GMC_CODE5 = GMC_CODE5 COLLATE DATABASE_DEFAULT
			,GMC_CODE6 = GMC_CODE6 COLLATE DATABASE_DEFAULT
			,PLANNED_ITU_ADMISSION
			,ACTION_ID
			,PLANNED_PROCEDURE_DATE
			,DATE_DISCREPANCY_REASON
			,ROOT_DECISION_DATE_COMMENTS = ROOT_DECISION_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,SurgicalAccessID
			,CCLGGuidelineName = CCLGGuidelineName COLLATE DATABASE_DEFAULT
			,TreatedToCCLGGuidelines
			,ConditioningRegimenPrimary
			,ConditioningRegimenSub1
			,ConditioningRegimenSub2
			,ResectionStatus
			,ASAGrade
			,AdjunctiveTherapyID
			,OtherTreatmentIntent = OtherTreatmentIntent COLLATE DATABASE_DEFAULT
			,TherapyType
			,SNOMEDProcedure
			,SNOMEDProcedure2
			,SNOMEDProcedure3
			,TertiaryReferralKey
			,StartTime
			,EndTime
			,RegionalAnaestheticTechnique
			,SNOMEDRTT
			,SNOMEDProcedure4
			,ROOT_PRIM_ADJUSTMENT_COMMENTS = ROOT_PRIM_ADJUSTMENT_COMMENTS  COLLATE DATABASE_DEFAULT
			,ROOT_SUBPRIM_ADJUSTMENT_COMMENTS = ROOT_SUBPRIM_ADJUSTMENT_COMMENTS COLLATE DATABASE_DEFAULT
	FROM	[CancerRegister_WSHT]..tblMAIN_SURGERY

		UNION ALL 

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(2 AS tinyint) AS SrcSysID
			,SURGERY_ID
			,CARE_ID
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,N7_1_SITE_CODE = N7_1_SITE_CODE COLLATE DATABASE_DEFAULT
			,N_SITE_CODE_DTT = N_SITE_CODE_DTT COLLATE DATABASE_DEFAULT
			,N7_2_CONSULTANT = N7_2_CONSULTANT COLLATE DATABASE_DEFAULT
			,N7_3_SPECIALTY
			,N7_4_TREATMENT_INTENT
			,N7_5_DECISION_DATE
			,N7_8_ADMISSION_DATE
			,N7_9_SURGERY_DATE
			,L_PROCEDURE_SITE
			,L_PROCEDURE_TYPE
			,L_PROCEDURE
			,L_PROCEDURE_SITE2
			,L_PROCEDURE_TYPE2
			,L_PROCEDURE2
			,L_PROCEDURE_SITE3
			,L_PROCEDURE_TYPE3
			,L_PROCEDURE3
			,L_PROCEDURE_SITE4
			,L_PROCEDURE_TYPE4
			,L_PROCEDURE4
			,N7_10_PROCEDURE_1 = N7_10_PROCEDURE_1 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_2 = N7_11_PROCEDURE_2 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_3 = N7_11_PROCEDURE_3 COLLATE DATABASE_DEFAULT
			,N7_11_PROCEDURE_4 = N7_11_PROCEDURE_4 COLLATE DATABASE_DEFAULT
			,N7_12_DISCHARGE_DATE
			,N7_13_DISCHARGE_DESTINATION
			,N_TREATMENT_EVENT = N_TREATMENT_EVENT COLLATE DATABASE_DEFAULT
			,N_TREATMENT_SETTING = N_TREATMENT_SETTING COLLATE DATABASE_DEFAULT
			,L_TRIAL
			,L_SURGEON = L_SURGEON COLLATE DATABASE_DEFAULT
			,L_SURGEON_NAME = L_SURGEON_NAME COLLATE DATABASE_DEFAULT
			,L_GRADE = L_GRADE COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_1 = L_ASSISTANT_1 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_NAME_1 = L_ASSISTANT_NAME_1 COLLATE DATABASE_DEFAULT
			,L_GRADE_1 = L_GRADE_1 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_2 = L_ASSISTANT_2 COLLATE DATABASE_DEFAULT
			,L_ASSISTANT_NAME_2 = L_ASSISTANT_NAME_2 COLLATE DATABASE_DEFAULT
			,L_GRADE_2 = L_GRADE_2 COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_NAME = L_ANAESTHETIST_NAME COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST = L_ANAESTHETIST COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_NAME_2 = L_ANAESTHETIST_NAME_2 COLLATE DATABASE_DEFAULT
			,L_ANAESTHETIST_2 = L_ANAESTHETIST_2 COLLATE DATABASE_DEFAULT
			,L_URGENCY = L_URGENCY COLLATE DATABASE_DEFAULT
			,L_ANASTOMOSIS = L_ANASTOMOSIS COLLATE DATABASE_DEFAULT
			,L_BLOOD_LOSS
			,L_SUPPORT = L_SUPPORT COLLATE DATABASE_DEFAULT
			,L_COMPLICATIONS
			,L_COMPLICATIONS2
			,L_COMPLICATIONS3
			,L_OTHER_COMP = L_OTHER_COMP COLLATE DATABASE_DEFAULT
			,L_POST_COMP = L_POST_COMP COLLATE DATABASE_DEFAULT
			,L_TRANSFER = L_TRANSFER COLLATE DATABASE_DEFAULT
			,L_DAYS
			,L_RETURN_ITU = L_RETURN_ITU COLLATE DATABASE_DEFAULT
			,L_REASON_RETURN = L_REASON_RETURN COLLATE DATABASE_DEFAULT
			,L_DAYS_BACK
			,DEFINITIVE_TREATMENT
			,CWT_PROFORMA
			,L_DISCHARGE_COMMENTS = L_DISCHARGE_COMMENTS COLLATE DATABASE_DEFAULT
			,STEM_CELL_INFUSION_SOURCE_ID
			,STEM_CELL_INFUSION_SOURCE_ID2
			,STEM_CELL_INFUSION_SOURCE_ID3
			,STEM_CELL_INFUSION_DONOR_ID
			,STEM_CELL_INFUSION_DONOR_ID2
			,STEM_CELL_INFUSION_DONOR_ID3
			,SURGEON_3 = SURGEON_3 COLLATE DATABASE_DEFAULT
			,SURGEON_3_GRADE = SURGEON_3_GRADE COLLATE DATABASE_DEFAULT
			,SURGEON_3_NAME = SURGEON_3_NAME COLLATE DATABASE_DEFAULT
			,SURGEON_4 = SURGEON_4 COLLATE DATABASE_DEFAULT
			,SURGEON_4_GRADE = SURGEON_4_GRADE COLLATE DATABASE_DEFAULT
			,SURGEON_4_NAME = SURGEON_4_NAME COLLATE DATABASE_DEFAULT
			,ROOT_ADMISSION_DATE_COMMENTS = ROOT_ADMISSION_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,ROOT_PERFORMED_DATE_COMMENTS = ROOT_PERFORMED_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,GMC_CODE1 = GMC_CODE1 COLLATE DATABASE_DEFAULT
			,GMC_CODE2 = GMC_CODE2 COLLATE DATABASE_DEFAULT
			,GMC_CODE3 = GMC_CODE3 COLLATE DATABASE_DEFAULT
			,GMC_CODE4 = GMC_CODE4 COLLATE DATABASE_DEFAULT
			,GMC_CODE5 = GMC_CODE5 COLLATE DATABASE_DEFAULT
			,GMC_CODE6 = GMC_CODE6 COLLATE DATABASE_DEFAULT
			,PLANNED_ITU_ADMISSION
			,ACTION_ID
			,PLANNED_PROCEDURE_DATE
			,DATE_DISCREPANCY_REASON
			,ROOT_DECISION_DATE_COMMENTS = ROOT_DECISION_DATE_COMMENTS COLLATE DATABASE_DEFAULT
			,SurgicalAccessID
			,CCLGGuidelineName = CCLGGuidelineName COLLATE DATABASE_DEFAULT
			,TreatedToCCLGGuidelines
			,ConditioningRegimenPrimary
			,ConditioningRegimenSub1
			,ConditioningRegimenSub2
			,ResectionStatus
			,ASAGrade
			,AdjunctiveTherapyID
			,OtherTreatmentIntent = OtherTreatmentIntent COLLATE DATABASE_DEFAULT
			,TherapyType
			,SNOMEDProcedure
			,SNOMEDProcedure2
			,SNOMEDProcedure3
			,TertiaryReferralKey
			,StartTime
			,EndTime
			,RegionalAnaestheticTechnique
			,SNOMEDRTT
			,SNOMEDProcedure4
			,ROOT_PRIM_ADJUSTMENT_COMMENTS = ROOT_PRIM_ADJUSTMENT_COMMENTS  COLLATE DATABASE_DEFAULT
			,ROOT_SUBPRIM_ADJUSTMENT_COMMENTS = ROOT_SUBPRIM_ADJUSTMENT_COMMENTS COLLATE DATABASE_DEFAULT
	FROM	[CancerRegister_BSUH]..tblMAIN_SURGERY
GO
