SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the newNBOCAP_POST_SURGERY_PATHOLOGIES SCR table 
CREATE VIEW [Merge_DM_MatchViews].[newNBOCAP_POST_SURGERY_PATHOLOGIES] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.newNBOCAP_POST_SURGERY_PATHOLOGIES 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.newNBOCAP_POST_SURGERY_PATHOLOGIES
GO
