SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblSTEM_CELL_INFUSION_SOURCE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblSTEM_CELL_INFUSION_SOURCE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblSTEM_CELL_INFUSION_SOURCE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblSTEM_CELL_INFUSION_SOURCE
GO
