SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblERECTILE_FUNCTION SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblERECTILE_FUNCTION] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblERECTILE_FUNCTION 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblERECTILE_FUNCTION
GO
