SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the lnkAO_REFERRAL_PATIENT_TYPE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[lnkAO_REFERRAL_PATIENT_TYPE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.lnkAO_REFERRAL_PATIENT_TYPE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.lnkAO_REFERRAL_PATIENT_TYPE
GO
