SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expPALHOSPS4ADMITDATAEXISTING SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expPALHOSPS4ADMITDATAEXISTING] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expPALHOSPS4ADMITDATAEXISTING 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expPALHOSPS4ADMITDATAEXISTING
GO
