SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblRETINOBLASTOMA_ASSESSMENT SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblRETINOBLASTOMA_ASSESSMENT] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblRETINOBLASTOMA_ASSESSMENT 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblRETINOBLASTOMA_ASSESSMENT
GO
