SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblTRANSPLANT_PLANNED SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblTRANSPLANT_PLANNED] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblTRANSPLANT_PLANNED 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblTRANSPLANT_PLANNED
GO
