SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblINPATIENT_ADMISSIONS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblINPATIENT_ADMISSIONS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblINPATIENT_ADMISSIONS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblINPATIENT_ADMISSIONS
GO
