SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblCHARLSON_CO_MORBIDITIES SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblCHARLSON_CO_MORBIDITIES] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblCHARLSON_CO_MORBIDITIES 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblCHARLSON_CO_MORBIDITIES
GO
