SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblUROLOGY_PREOP_DIAGNOSIS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblUROLOGY_PREOP_DIAGNOSIS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblUROLOGY_PREOP_DIAGNOSIS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblUROLOGY_PREOP_DIAGNOSIS
GO
