SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblSPINAL_CORD_COMPRESSION SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tblSPINAL_CORD_COMPRESSION] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblSPINAL_CORD_COMPRESSION 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblSPINAL_CORD_COMPRESSION
GO
