SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblAO_ADMINISTRATION_SERVICE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblAO_ADMINISTRATION_SERVICE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblAO_ADMINISTRATION_SERVICE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblAO_ADMINISTRATION_SERVICE
GO
