SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expCUP_REASON_STRING_CONCAT SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expCUP_REASON_STRING_CONCAT] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expCUP_REASON_STRING_CONCAT 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expCUP_REASON_STRING_CONCAT
GO
