SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblSAR_LOCATION_TISSUE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblSAR_LOCATION_TISSUE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblSAR_LOCATION_TISSUE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblSAR_LOCATION_TISSUE
GO
