SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the DEPRECIATED_18_02_ltblNBOCAP_PREFERRED_SURGERY SCR table 

CREATE VIEW [Merge_DM_MatchViews].[DEPRECIATED_18_02_ltblNBOCAP_PREFERRED_SURGERY] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.DEPRECIATED_18_02_ltblNBOCAP_PREFERRED_SURGERY 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.DEPRECIATED_18_02_ltblNBOCAP_PREFERRED_SURGERY
GO
