SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tmpPALLIATIVE_CARE_DOWNLOAD SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tmpPALLIATIVE_CARE_DOWNLOAD] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tmpPALLIATIVE_CARE_DOWNLOAD 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tmpPALLIATIVE_CARE_DOWNLOAD
GO
