SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblTERTIARY_REFERRALS_LEGACY_DATE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblTERTIARY_REFERRALS_LEGACY_DATE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblTERTIARY_REFERRALS_LEGACY_DATE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblTERTIARY_REFERRALS_LEGACY_DATE
GO
