SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblASSESSMENT_GYNAECOLOGY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblASSESSMENT_GYNAECOLOGY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblASSESSMENT_GYNAECOLOGY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblASSESSMENT_GYNAECOLOGY
GO
