SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblBAUS_NEPH_SITE_OF_RECURRENCE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblBAUS_NEPH_SITE_OF_RECURRENCE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblBAUS_NEPH_SITE_OF_RECURRENCE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblBAUS_NEPH_SITE_OF_RECURRENCE
GO
