SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblASSESSMENT_HN_LONG_TERM_COMPS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblASSESSMENT_HN_LONG_TERM_COMPS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblASSESSMENT_HN_LONG_TERM_COMPS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblASSESSMENT_HN_LONG_TERM_COMPS
GO
