SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expPALOPS6ADMITDATAEXISTING SCR table 

CREATE VIEW [Merge_DM_MatchViews].[expPALOPS6ADMITDATAEXISTING] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expPALOPS6ADMITDATAEXISTING 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expPALOPS6ADMITDATAEXISTING
GO
