SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPROSTATECTOMY_PREV_MANAGEMENT SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblPROSTATECTOMY_PREV_MANAGEMENT] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblPROSTATECTOMY_PREV_MANAGEMENT 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblPROSTATECTOMY_PREV_MANAGEMENT
GO
