SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expPALOPS6ADMITDATANEW SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expPALOPS6ADMITDATANEW] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.expPALOPS6ADMITDATANEW 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.expPALOPS6ADMITDATANEW
GO
