SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblSARCOMA_SURGICAL_MARGIN_ADEQUACY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblSARCOMA_SURGICAL_MARGIN_ADEQUACY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblSARCOMA_SURGICAL_MARGIN_ADEQUACY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblSARCOMA_SURGICAL_MARGIN_ADEQUACY
GO
