SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblTNM_VERSION_HISTORY_GLOBAL SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tblTNM_VERSION_HISTORY_GLOBAL] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblTNM_VERSION_HISTORY_GLOBAL 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblTNM_VERSION_HISTORY_GLOBAL
GO
