SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblASSESSMENT_HN_INV_ORD_SITES SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblASSESSMENT_HN_INV_ORD_SITES] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblASSESSMENT_HN_INV_ORD_SITES 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblASSESSMENT_HN_INV_ORD_SITES
GO
