SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblAO_NEUTROPENIC_SEPSIS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblAO_NEUTROPENIC_SEPSIS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblAO_NEUTROPENIC_SEPSIS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblAO_NEUTROPENIC_SEPSIS
GO
