SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the NBOCAP_MAPPING_TEMP SCR table 
CREATE VIEW [Merge_DM_MatchViews].[NBOCAP_MAPPING_TEMP] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.NBOCAP_MAPPING_TEMP 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.NBOCAP_MAPPING_TEMP
GO
