SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the newNBOCAP_CHEMORADIOTHERAPY_NO_SURGERY SCR table 

CREATE VIEW [Merge_DM_MatchViews].[newNBOCAP_CHEMORADIOTHERAPY_NO_SURGERY] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.newNBOCAP_CHEMORADIOTHERAPY_NO_SURGERY 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.newNBOCAP_CHEMORADIOTHERAPY_NO_SURGERY
GO
