SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblPALLIATIVE_EPISODE_INPATIENT SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblPALLIATIVE_EPISODE_INPATIENT] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblPALLIATIVE_EPISODE_INPATIENT 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblPALLIATIVE_EPISODE_INPATIENT
GO
