SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblSNOMED_HAEMATOLOGY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblSNOMED_HAEMATOLOGY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblSNOMED_HAEMATOLOGY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblSNOMED_HAEMATOLOGY
GO
