SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPERSON_STATED_GENDER SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblPERSON_STATED_GENDER] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblPERSON_STATED_GENDER 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblPERSON_STATED_GENDER
GO
