SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblCHEMO_ADMINISTRATION_ROUTE SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblCHEMO_ADMINISTRATION_ROUTE] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblCHEMO_ADMINISTRATION_ROUTE 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblCHEMO_ADMINISTRATION_ROUTE
GO
