SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPALLIATIVE_CARE_PLAN_OFFERED SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblPALLIATIVE_CARE_PLAN_OFFERED] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblPALLIATIVE_CARE_PLAN_OFFERED 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblPALLIATIVE_CARE_PLAN_OFFERED
GO
