SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblNBOCAP_PREFERRED_SURGERY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblNBOCAP_PREFERRED_SURGERY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblNBOCAP_PREFERRED_SURGERY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblNBOCAP_PREFERRED_SURGERY
GO
