SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblPATHOLOGY_GYNAECOLOGY SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tblPATHOLOGY_GYNAECOLOGY] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblPATHOLOGY_GYNAECOLOGY 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblPATHOLOGY_GYNAECOLOGY
GO
