SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [Merge_DM_MatchViews].[tblDEMOGRAPHICS] AS

/******************************************************** © Copyright & Licensing ****************************************************************
© 2019 Perspicacity Ltd & Brighton & Sussex University Hospitals

This code / file is part of Perspicacity & BSUH's Cancer Data Warehouse & Reporting suite.

This Cancer Data Warehouse & Reporting suite is free software: you can 
redistribute it and/or modify it under the terms of the GNU Affero 
General Public License as published by the Free Software Foundation, 
either version 3 of the License, or (at your option) any later version.

This Cancer Data Warehouse & Reporting suite is distributed in the hope 
that it will be useful, but WITHOUT ANY WARRANTY; without even the 
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

A full copy of this code can be found at https://github.com/BrightonSussexUniHospitals/CancerReportingSuite

You may also be interested in the other repositories at https://github.com/perspicacity-ltd or
https://github.com/BrightonSussexUniHospitals

Original Work Created Date:	30/07/2020
Original Work Created By:	Perspicacity Ltd (Matthew Bishop) & BSUH (Lawrence Simpson)
Original Work Contact:		07545 878906
Original Work Contact:		matthew.bishop@perspicacityltd.co.uk / lawrencesimpson@nhs.net
Description:				Create a local config view to point at the place where the SCR
							replicated data is located so that the core procedures don't
							need to be changed when they are copied to different environments 
							(e.g. live vs test or from one trust to another)
**************************************************************************************************************************************************/

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(1 AS tinyint) AS SrcSysID
			,PATIENT_ID
			,N1_1_NHS_NUMBER = N1_1_NHS_NUMBER COLLATE DATABASE_DEFAULT
			,NHS_NUMBER_STATUS = NHS_NUMBER_STATUS COLLATE DATABASE_DEFAULT
			,L_RA3_RID = L_RA3_RID COLLATE DATABASE_DEFAULT
			,L_RA7_RID = L_RA7_RID COLLATE DATABASE_DEFAULT
			,L_RVJ01_RID = L_RVJ01_RID COLLATE DATABASE_DEFAULT
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,L_NSTS_STATUS
			,N1_2_HOSPITAL_NUMBER = N1_2_HOSPITAL_NUMBER COLLATE DATABASE_DEFAULT
			,L_TITLE
			,N1_5_SURNAME = N1_5_SURNAME COLLATE DATABASE_DEFAULT
			,N1_6_FORENAME = N1_6_FORENAME COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_1 = N1_7_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_2 = N1_7_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_3 = N1_7_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_4 = N1_7_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_5 = N1_7_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,N1_8_POSTCODE = N1_8_POSTCODE COLLATE DATABASE_DEFAULT
			,N1_9_SEX = N1_9_SEX COLLATE DATABASE_DEFAULT
			,N1_10_DATE_BIRTH
			,N1_11_GP_CODE = N1_11_GP_CODE COLLATE DATABASE_DEFAULT
			,N1_12_GP_PRACTICE_CODE = N1_12_GP_PRACTICE_CODE COLLATE DATABASE_DEFAULT
			,N1_13_PCT = N1_13_PCT COLLATE DATABASE_DEFAULT
			,N1_14_SURNAME_BIRTH = N1_14_SURNAME_BIRTH COLLATE DATABASE_DEFAULT
			,N1_15_ETHNICITY = N1_15_ETHNICITY COLLATE DATABASE_DEFAULT
			,PAT_PREF_NAME = PAT_PREF_NAME COLLATE DATABASE_DEFAULT
			,PAT_OCCUPATION = PAT_OCCUPATION COLLATE DATABASE_DEFAULT
			,PAT_SOCIAL_CLASS = PAT_SOCIAL_CLASS COLLATE DATABASE_DEFAULT
			,PAT_LIVES_ALONE
			,MARITAL_STATUS = MARITAL_STATUS COLLATE DATABASE_DEFAULT
			,PAT_PREF_LANGUAGE = PAT_PREF_LANGUAGE COLLATE DATABASE_DEFAULT
			,PAT_PREF_CONTACT
			,L_DEATH_STATUS
			,N15_1_DATE_DEATH
			,N15_2_DEATH_LOCATION
			,N15_3_DEATH_CAUSE
			,N15_4_DEATH_CANCER
			,N15_5_DEATH_CODE_1 = N15_5_DEATH_CODE_1 COLLATE DATABASE_DEFAULT
			,N15_6_DEATH_CODE_2 = N15_6_DEATH_CODE_2 COLLATE DATABASE_DEFAULT
			,N15_7_DEATH_CODE_3 = N15_7_DEATH_CODE_3 COLLATE DATABASE_DEFAULT
			,N15_8_DEATH_CODE_4 = N15_8_DEATH_CODE_4 COLLATE DATABASE_DEFAULT
			,N15_9_DEATH_DISCREPANCY
			,N_CC4_TOWN = N_CC4_TOWN COLLATE DATABASE_DEFAULT
			,N_CC5_COUNTRY = N_CC5_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC6_M_SURNAME = N_CC6_M_SURNAME COLLATE DATABASE_DEFAULT
			,N_CC7_M_CLASS = N_CC7_M_CLASS COLLATE DATABASE_DEFAULT
			,N_CC8_M_FORENAME = N_CC8_M_FORENAME COLLATE DATABASE_DEFAULT
			,N_CC9_M_DOB
			,N_CC10_M_TOWN = N_CC10_M_TOWN COLLATE DATABASE_DEFAULT
			,N_CC11_M_COUNTRY = N_CC11_M_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC12_M_OCC = N_CC12_M_OCC COLLATE DATABASE_DEFAULT
			,N_CC13_M_OCC_DIAG = N_CC13_M_OCC_DIAG COLLATE DATABASE_DEFAULT
			,N_CC6_F_SURNAME = N_CC6_F_SURNAME COLLATE DATABASE_DEFAULT
			,N_CC7_F_CLASS = N_CC7_F_CLASS COLLATE DATABASE_DEFAULT
			,N_CC8_F_FORENAME = N_CC8_F_FORENAME COLLATE DATABASE_DEFAULT
			,N_CC9_F_DOB
			,N_CC10_F_TOWN = N_CC10_F_TOWN COLLATE DATABASE_DEFAULT
			,N_CC11_F_COUNTRY = N_CC11_F_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC12_F_OCC = N_CC12_F_OCC COLLATE DATABASE_DEFAULT
			,N_CC13_F_OCC_DIAG = N_CC13_F_OCC_DIAG COLLATE DATABASE_DEFAULT
			,N_CC14_MULTI_BIRTH
			,R_POST_MORTEM
			,R_DAY_PHONE = R_DAY_PHONE COLLATE DATABASE_DEFAULT
			,DAY_PHONE_EXT = DAY_PHONE_EXT COLLATE DATABASE_DEFAULT
			,R_EVE_PHONE = R_EVE_PHONE COLLATE DATABASE_DEFAULT
			,EVE_PHONE_EXT = EVE_PHONE_EXT COLLATE DATABASE_DEFAULT
			,R_DEATH_TREATMENT = R_DEATH_TREATMENT COLLATE DATABASE_DEFAULT
			,R_PM_DETAILS = R_PM_DETAILS COLLATE DATABASE_DEFAULT
			,L_IATROGENIC_DEATH
			,L_INFECTION_DEATH
			,L_DEATH_COMMENTS = L_DEATH_COMMENTS COLLATE DATABASE_DEFAULT
			,RELIGION
			,CONTACT_DETAILS = CONTACT_DETAILS COLLATE DATABASE_DEFAULT
			,NOK_NAME = NOK_NAME COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_1 = NOK_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_2 = NOK_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_3 = NOK_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_4 = NOK_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_5 = NOK_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,NOK_POSTCODE = NOK_POSTCODE COLLATE DATABASE_DEFAULT
			,NOK_CONTACT = NOK_CONTACT COLLATE DATABASE_DEFAULT
			,NOK_RELATIONSHIP = NOK_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,PAT_DEPENDANTS = PAT_DEPENDANTS COLLATE DATABASE_DEFAULT
			,CARER_NAME = CARER_NAME COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_1 = CARER_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_2 = CARER_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_3 = CARER_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_4 = CARER_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_5 = CARER_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,CARER_POSTCODE = CARER_POSTCODE COLLATE DATABASE_DEFAULT
			,CARER_CONTACT = CARER_CONTACT COLLATE DATABASE_DEFAULT
			,CARER_RELATIONSHIP = CARER_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,CARER1_TYPE = CARER1_TYPE COLLATE DATABASE_DEFAULT
			,CARER2_NAME = CARER2_NAME COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_1 = CARER2_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_2 = CARER2_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_3 = CARER2_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_4 = CARER2_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_5 = CARER2_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,CARER2_POSTCODE = CARER2_POSTCODE COLLATE DATABASE_DEFAULT
			,CARER2_CONTACT = CARER2_CONTACT COLLATE DATABASE_DEFAULT
			,CARER2_RELATIONSHIP = CARER2_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,CARER2_TYPE = CARER2_TYPE COLLATE DATABASE_DEFAULT
			,PT_AT_RISK
			,REASON_RISK = REASON_RISK COLLATE DATABASE_DEFAULT
			,GESTATION = GESTATION COLLATE DATABASE_DEFAULT
			,CAUSE_OF_DEATH_UROLOGY
			,AVOIDABLE_DEATH
			,AVOIDABLE_DETAILS = AVOIDABLE_DETAILS COLLATE DATABASE_DEFAULT
			,OTHER_DEATH_CAUSE_UROLOGY = OTHER_DEATH_CAUSE_UROLOGY COLLATE DATABASE_DEFAULT
			,ACTION_ID
			,STATED_GENDER_CODE = STATED_GENDER_CODE COLLATE DATABASE_DEFAULT
			,CAUSE_OF_DEATH_UROLOGY_FUP
			,DEATH_WITHIN_30_DAYS_OF_TREAT
			,DEATH_CAUSE_WITHIN_30_DAYS_OF_TREAT
			,DEATH_CAUSE_LATER_DATE
			,RegisteredPractice
			,RegisteredGP
			,PersonSexualOrientation
	FROM  [WSHT_Deduplication]..tblDEMOGRAPHICS

		UNION ALL 

	-- Select a replica dataset from a V22.2 table
	SELECT  CAST(2 AS tinyint) AS SrcSysID
			,PATIENT_ID
			,N1_1_NHS_NUMBER = N1_1_NHS_NUMBER COLLATE DATABASE_DEFAULT
			,NHS_NUMBER_STATUS = NHS_NUMBER_STATUS COLLATE DATABASE_DEFAULT
			,L_RA3_RID = L_RA3_RID COLLATE DATABASE_DEFAULT
			,L_RA7_RID = L_RA7_RID COLLATE DATABASE_DEFAULT
			,L_RVJ01_RID = L_RVJ01_RID COLLATE DATABASE_DEFAULT
			,TEMP_ID = TEMP_ID COLLATE DATABASE_DEFAULT
			,L_NSTS_STATUS
			,N1_2_HOSPITAL_NUMBER = N1_2_HOSPITAL_NUMBER COLLATE DATABASE_DEFAULT
			,L_TITLE
			,N1_5_SURNAME = N1_5_SURNAME COLLATE DATABASE_DEFAULT
			,N1_6_FORENAME = N1_6_FORENAME COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_1 = N1_7_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_2 = N1_7_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_3 = N1_7_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_4 = N1_7_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,N1_7_ADDRESS_5 = N1_7_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,N1_8_POSTCODE = N1_8_POSTCODE COLLATE DATABASE_DEFAULT
			,N1_9_SEX = N1_9_SEX COLLATE DATABASE_DEFAULT
			,N1_10_DATE_BIRTH
			,N1_11_GP_CODE = N1_11_GP_CODE COLLATE DATABASE_DEFAULT
			,N1_12_GP_PRACTICE_CODE = N1_12_GP_PRACTICE_CODE COLLATE DATABASE_DEFAULT
			,N1_13_PCT = N1_13_PCT COLLATE DATABASE_DEFAULT
			,N1_14_SURNAME_BIRTH = N1_14_SURNAME_BIRTH COLLATE DATABASE_DEFAULT
			,N1_15_ETHNICITY = N1_15_ETHNICITY COLLATE DATABASE_DEFAULT
			,PAT_PREF_NAME = PAT_PREF_NAME COLLATE DATABASE_DEFAULT
			,PAT_OCCUPATION = PAT_OCCUPATION COLLATE DATABASE_DEFAULT
			,PAT_SOCIAL_CLASS = PAT_SOCIAL_CLASS COLLATE DATABASE_DEFAULT
			,PAT_LIVES_ALONE
			,MARITAL_STATUS = MARITAL_STATUS COLLATE DATABASE_DEFAULT
			,PAT_PREF_LANGUAGE = PAT_PREF_LANGUAGE COLLATE DATABASE_DEFAULT
			,PAT_PREF_CONTACT
			,L_DEATH_STATUS
			,N15_1_DATE_DEATH
			,N15_2_DEATH_LOCATION
			,N15_3_DEATH_CAUSE
			,N15_4_DEATH_CANCER
			,N15_5_DEATH_CODE_1 = N15_5_DEATH_CODE_1 COLLATE DATABASE_DEFAULT
			,N15_6_DEATH_CODE_2 = N15_6_DEATH_CODE_2 COLLATE DATABASE_DEFAULT
			,N15_7_DEATH_CODE_3 = N15_7_DEATH_CODE_3 COLLATE DATABASE_DEFAULT
			,N15_8_DEATH_CODE_4 = N15_8_DEATH_CODE_4 COLLATE DATABASE_DEFAULT
			,N15_9_DEATH_DISCREPANCY
			,N_CC4_TOWN = N_CC4_TOWN COLLATE DATABASE_DEFAULT
			,N_CC5_COUNTRY = N_CC5_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC6_M_SURNAME = N_CC6_M_SURNAME COLLATE DATABASE_DEFAULT
			,N_CC7_M_CLASS = N_CC7_M_CLASS COLLATE DATABASE_DEFAULT
			,N_CC8_M_FORENAME = N_CC8_M_FORENAME COLLATE DATABASE_DEFAULT
			,N_CC9_M_DOB
			,N_CC10_M_TOWN = N_CC10_M_TOWN COLLATE DATABASE_DEFAULT
			,N_CC11_M_COUNTRY = N_CC11_M_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC12_M_OCC = N_CC12_M_OCC COLLATE DATABASE_DEFAULT
			,N_CC13_M_OCC_DIAG = N_CC13_M_OCC_DIAG COLLATE DATABASE_DEFAULT
			,N_CC6_F_SURNAME = N_CC6_F_SURNAME COLLATE DATABASE_DEFAULT
			,N_CC7_F_CLASS = N_CC7_F_CLASS COLLATE DATABASE_DEFAULT
			,N_CC8_F_FORENAME = N_CC8_F_FORENAME COLLATE DATABASE_DEFAULT
			,N_CC9_F_DOB
			,N_CC10_F_TOWN = N_CC10_F_TOWN COLLATE DATABASE_DEFAULT
			,N_CC11_F_COUNTRY = N_CC11_F_COUNTRY COLLATE DATABASE_DEFAULT
			,N_CC12_F_OCC = N_CC12_F_OCC COLLATE DATABASE_DEFAULT
			,N_CC13_F_OCC_DIAG = N_CC13_F_OCC_DIAG COLLATE DATABASE_DEFAULT
			,N_CC14_MULTI_BIRTH
			,R_POST_MORTEM
			,R_DAY_PHONE = R_DAY_PHONE COLLATE DATABASE_DEFAULT
			,DAY_PHONE_EXT = DAY_PHONE_EXT COLLATE DATABASE_DEFAULT
			,R_EVE_PHONE = R_EVE_PHONE COLLATE DATABASE_DEFAULT
			,EVE_PHONE_EXT = EVE_PHONE_EXT COLLATE DATABASE_DEFAULT
			,R_DEATH_TREATMENT = R_DEATH_TREATMENT COLLATE DATABASE_DEFAULT
			,R_PM_DETAILS = R_PM_DETAILS COLLATE DATABASE_DEFAULT
			,L_IATROGENIC_DEATH
			,L_INFECTION_DEATH
			,L_DEATH_COMMENTS = L_DEATH_COMMENTS COLLATE DATABASE_DEFAULT
			,RELIGION
			,CONTACT_DETAILS = CONTACT_DETAILS COLLATE DATABASE_DEFAULT
			,NOK_NAME = NOK_NAME COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_1 = NOK_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_2 = NOK_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_3 = NOK_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_4 = NOK_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,NOK_ADDRESS_5 = NOK_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,NOK_POSTCODE = NOK_POSTCODE COLLATE DATABASE_DEFAULT
			,NOK_CONTACT = NOK_CONTACT COLLATE DATABASE_DEFAULT
			,NOK_RELATIONSHIP = NOK_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,PAT_DEPENDANTS = PAT_DEPENDANTS COLLATE DATABASE_DEFAULT
			,CARER_NAME = CARER_NAME COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_1 = CARER_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_2 = CARER_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_3 = CARER_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_4 = CARER_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,CARER_ADDRESS_5 = CARER_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,CARER_POSTCODE = CARER_POSTCODE COLLATE DATABASE_DEFAULT
			,CARER_CONTACT = CARER_CONTACT COLLATE DATABASE_DEFAULT
			,CARER_RELATIONSHIP = CARER_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,CARER1_TYPE = CARER1_TYPE COLLATE DATABASE_DEFAULT
			,CARER2_NAME = CARER2_NAME COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_1 = CARER2_ADDRESS_1 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_2 = CARER2_ADDRESS_2 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_3 = CARER2_ADDRESS_3 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_4 = CARER2_ADDRESS_4 COLLATE DATABASE_DEFAULT
			,CARER2_ADDRESS_5 = CARER2_ADDRESS_5 COLLATE DATABASE_DEFAULT
			,CARER2_POSTCODE = CARER2_POSTCODE COLLATE DATABASE_DEFAULT
			,CARER2_CONTACT = CARER2_CONTACT COLLATE DATABASE_DEFAULT
			,CARER2_RELATIONSHIP = CARER2_RELATIONSHIP COLLATE DATABASE_DEFAULT
			,CARER2_TYPE = CARER2_TYPE COLLATE DATABASE_DEFAULT
			,PT_AT_RISK
			,REASON_RISK = REASON_RISK COLLATE DATABASE_DEFAULT
			,GESTATION = GESTATION COLLATE DATABASE_DEFAULT
			,CAUSE_OF_DEATH_UROLOGY
			,AVOIDABLE_DEATH
			,AVOIDABLE_DETAILS = AVOIDABLE_DETAILS COLLATE DATABASE_DEFAULT
			,OTHER_DEATH_CAUSE_UROLOGY = OTHER_DEATH_CAUSE_UROLOGY COLLATE DATABASE_DEFAULT
			,ACTION_ID
			,STATED_GENDER_CODE = STATED_GENDER_CODE COLLATE DATABASE_DEFAULT
			,CAUSE_OF_DEATH_UROLOGY_FUP
			,DEATH_WITHIN_30_DAYS_OF_TREAT
			,DEATH_CAUSE_WITHIN_30_DAYS_OF_TREAT
			,DEATH_CAUSE_LATER_DATE
			,RegisteredPractice
			,RegisteredGP
			,PersonSexualOrientation
	FROM  [BSUH_Deduplication]..tblDEMOGRAPHICS
GO
