SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expPALCCS3ADMITDATANEW SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expPALCCS3ADMITDATANEW] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expPALCCS3ADMITDATANEW 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expPALCCS3ADMITDATANEW
GO
