SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblPATHOLOGY_DERMATOLOGY SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tblPATHOLOGY_DERMATOLOGY] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblPATHOLOGY_DERMATOLOGY 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblPATHOLOGY_DERMATOLOGY
GO
