SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblINITIAL_PAEDIATRICS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblINITIAL_PAEDIATRICS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblINITIAL_PAEDIATRICS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblINITIAL_PAEDIATRICS
GO
