SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblFAMILIAL_CANCER_SYNDROME SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblFAMILIAL_CANCER_SYNDROME] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblFAMILIAL_CANCER_SYNDROME 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblFAMILIAL_CANCER_SYNDROME
GO
