SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblNOT_DISCUSSED_REASON SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblNOT_DISCUSSED_REASON] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblNOT_DISCUSSED_REASON 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblNOT_DISCUSSED_REASON
GO
