SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPAL_LOCATION_FROMTO SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblPAL_LOCATION_FROMTO] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblPAL_LOCATION_FROMTO 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblPAL_LOCATION_FROMTO
GO
