SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expROOT_REFERRAL_DATA SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expROOT_REFERRAL_DATA] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.expROOT_REFERRAL_DATA 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.expROOT_REFERRAL_DATA
GO
