SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblSKIN_LESION_DIAGNOSIS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblSKIN_LESION_DIAGNOSIS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblSKIN_LESION_DIAGNOSIS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblSKIN_LESION_DIAGNOSIS
GO
