SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expPALOPS2ADMITDATANEW SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expPALOPS2ADMITDATANEW] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expPALOPS2ADMITDATANEW 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expPALOPS2ADMITDATANEW
GO
