SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblHOSPITAL_NUMBERS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblHOSPITAL_NUMBERS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblHOSPITAL_NUMBERS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblHOSPITAL_NUMBERS
GO
