SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblAO_DISCHARGE_DESTINATION SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblAO_DISCHARGE_DESTINATION] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblAO_DISCHARGE_DESTINATION 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblAO_DISCHARGE_DESTINATION
GO
