SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblINCOMPLETE_REASON SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblINCOMPLETE_REASON] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblINCOMPLETE_REASON 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblINCOMPLETE_REASON
GO
