SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblANN_ARBOR_EXTRANODALITY SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblANN_ARBOR_EXTRANODALITY] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblANN_ARBOR_EXTRANODALITY 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblANN_ARBOR_EXTRANODALITY
GO
