SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblSPINAL_CORD_COMPRESSION SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblSPINAL_CORD_COMPRESSION] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblSPINAL_CORD_COMPRESSION 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblSPINAL_CORD_COMPRESSION
GO
