SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the rptNMBRA_OPERATION_TEMP SCR table 
CREATE VIEW [Merge_DM_MatchViews].[rptNMBRA_OPERATION_TEMP] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.rptNMBRA_OPERATION_TEMP 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.rptNMBRA_OPERATION_TEMP
GO
