SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblCYTOGENETICS_RHABDOMYOSARCOMA SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblCYTOGENETICS_RHABDOMYOSARCOMA] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblCYTOGENETICS_RHABDOMYOSARCOMA 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblCYTOGENETICS_RHABDOMYOSARCOMA
GO
