SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the lnkBAUS_SURVEILLANCE_REASON SCR table 
CREATE VIEW [Merge_DM_MatchViews].[lnkBAUS_SURVEILLANCE_REASON] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.lnkBAUS_SURVEILLANCE_REASON 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.lnkBAUS_SURVEILLANCE_REASON
GO
