SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPALLIATIVE_INVESTIGATIONS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblPALLIATIVE_INVESTIGATIONS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblPALLIATIVE_INVESTIGATIONS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblPALLIATIVE_INVESTIGATIONS
GO
