SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblLOCAL_DOWNLOAD_FIELDNAMES SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblLOCAL_DOWNLOAD_FIELDNAMES] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblLOCAL_DOWNLOAD_FIELDNAMES 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblLOCAL_DOWNLOAD_FIELDNAMES
GO
