SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblREASON_NOT_PERFORMED SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblREASON_NOT_PERFORMED] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblREASON_NOT_PERFORMED 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblREASON_NOT_PERFORMED
GO
