SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblBREAST_NOT_IMMEDIATE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblBREAST_NOT_IMMEDIATE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblBREAST_NOT_IMMEDIATE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblBREAST_NOT_IMMEDIATE
GO
