SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblUNPLANNED_RETURN_TO_THEATRE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblUNPLANNED_RETURN_TO_THEATRE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblUNPLANNED_RETURN_TO_THEATRE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblUNPLANNED_RETURN_TO_THEATRE
GO
