SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the lnkPAL_REF_INVESTIGATIONS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[lnkPAL_REF_INVESTIGATIONS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.lnkPAL_REF_INVESTIGATIONS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.lnkPAL_REF_INVESTIGATIONS
GO
