SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblHAEM_RELAPSE_TRANSFORM SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblHAEM_RELAPSE_TRANSFORM] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblHAEM_RELAPSE_TRANSFORM 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblHAEM_RELAPSE_TRANSFORM
GO
