SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblPALLIATIVE_EPISODE_OUTPATIENT SCR table 
CREATE VIEW [Merge_DM_MatchViews].[tblPALLIATIVE_EPISODE_OUTPATIENT] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.tblPALLIATIVE_EPISODE_OUTPATIENT 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.tblPALLIATIVE_EPISODE_OUTPATIENT
GO
