SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblRETINOBLASTOMA_LATERALITY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblRETINOBLASTOMA_LATERALITY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblRETINOBLASTOMA_LATERALITY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblRETINOBLASTOMA_LATERALITY
GO
