SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblIMAGING_ANATOMICAL_CODE SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblIMAGING_ANATOMICAL_CODE] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblIMAGING_ANATOMICAL_CODE 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblIMAGING_ANATOMICAL_CODE
GO
