SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the newNBOCAP_QUALIFYING_CARE_PLANS SCR table 
CREATE VIEW [Merge_DM_MatchViews].[newNBOCAP_QUALIFYING_CARE_PLANS] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.newNBOCAP_QUALIFYING_CARE_PLANS 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.newNBOCAP_QUALIFYING_CARE_PLANS
GO
