SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the lnkBAUS_ASSESSMENT_INTERVENTION SCR table 
CREATE VIEW [Merge_DM_MatchViews].[lnkBAUS_ASSESSMENT_INTERVENTION] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.lnkBAUS_ASSESSMENT_INTERVENTION 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.lnkBAUS_ASSESSMENT_INTERVENTION
GO
