SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the tblDERMATOLOGY_RECURRENCES SCR table 

CREATE VIEW [Merge_DM_MatchViews].[tblDERMATOLOGY_RECURRENCES] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.tblDERMATOLOGY_RECURRENCES 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.tblDERMATOLOGY_RECURRENCES
GO
