SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPALLIATIVE_EPISODE_RESIDENCE SCR table 

CREATE VIEW [Merge_DM_MatchViews].[ltblPALLIATIVE_EPISODE_RESIDENCE] AS 

 

SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblPALLIATIVE_EPISODE_RESIDENCE 

 

UNION ALL 

 

SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblPALLIATIVE_EPISODE_RESIDENCE
GO
