SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblTREATMENT_TOXICITIES SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblTREATMENT_TOXICITIES] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblTREATMENT_TOXICITIES 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblTREATMENT_TOXICITIES
GO
