SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the expSWCIS_TELETHERAPY_TEMP SCR table 
CREATE VIEW [Merge_DM_MatchViews].[expSWCIS_TELETHERAPY_TEMP] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.expSWCIS_TELETHERAPY_TEMP 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.expSWCIS_TELETHERAPY_TEMP
GO
