SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPALLIATIVE_PREF_PLACE_DEATH SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblPALLIATIVE_PREF_PLACE_DEATH] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM BSUH_Deduplication.dbo.ltblPALLIATIVE_PREF_PLACE_DEATH 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM WSHT_Deduplication.dbo.ltblPALLIATIVE_PREF_PLACE_DEATH
GO
