SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- Create a view to union the data for the ltblPALLIATIVE_CONTACT_SEEN_BY SCR table 
CREATE VIEW [Merge_DM_MatchViews].[ltblPALLIATIVE_CONTACT_SEEN_BY] AS 
 
SELECT CAST(2 AS TINYINT) AS SrcSysID, * FROM CancerRegister_BSUH.dbo.ltblPALLIATIVE_CONTACT_SEEN_BY 
 
UNION ALL 
 
SELECT CAST(1 AS TINYINT) AS SrcSysID, * FROM CancerRegister_WSHT.dbo.ltblPALLIATIVE_CONTACT_SEEN_BY
GO
