CREATE TABLE [map].[AspNetUsers_CouldBeMatch_01]
(
[SrcSysID_A] [tinyint] NOT NULL,
[Id_A] [int] NOT NULL,
[SrcSysID_B] [tinyint] NOT NULL,
[Id_B] [int] NOT NULL,
[SrcSysID_Master] [tinyint] NOT NULL,
[ID_Master] [int] NOT NULL,
[MatchScore] [int] NULL,
[MatchUsername] [int] NOT NULL,
[MatchEmail] [int] NOT NULL,
[MatchFullName] [int] NOT NULL,
[MatchOrgCode] [int] NOT NULL,
[Email_A] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[Email_B] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[FullName_A] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FullName_B] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[OrganisationCode_A] [nvarchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrganisationCode_B] [nvarchar] (5) COLLATE Latin1_General_CI_AS NULL,
[IsApproved_A] [bit] NULL,
[IsApproved_B] [bit] NULL,
[CreatedDate_A] [datetime] NULL,
[LastLoginDate_A] [datetime] NULL,
[LastPasswordChangeDate_A] [datetime] NULL,
[PasswordReset_A] [bit] NULL,
[AssociatedCNSId_A] [int] NULL,
[LastLockoutDate_A] [datetime] NULL,
[CreatedDate_B] [datetime] NULL,
[LastLoginDate_B] [datetime] NULL,
[LastPasswordChangeDate_B] [datetime] NULL,
[PasswordReset_B] [bit] NULL,
[AssociatedCNSId_B] [int] NULL,
[LastLockoutDate_B] [datetime] NULL
) ON [PRIMARY]
GO
