CREATE TABLE [Merge_R_Compare].[dbo_tblMAIN_PALLIATIVE]
(
[DW_tblMAIN_PALLIATIVE_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[PALL_ID] [int] NULL,
[CARE_ID] [int] NULL,
[TEMP_ID] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[N12_1_DECISION_DATE] [smalldatetime] NULL,
[N12_2_START_DATE] [smalldatetime] NULL,
[N1_3_ORG_CODE_TREATMENT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_SITE_CODE_DTT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_L39_PROVIDER] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_L40_COMMUNITY] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_L41_TREATMENT] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N_L42_TREAT_DATE] [smalldatetime] NULL,
[N_TREATMENT_EVENT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_SETTING] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_SPECIALIST] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[L_TRIAL] [int] NULL,
[DEFINITIVE_TREATMENT] [int] NULL,
[CWT_PROFORMA] [int] NULL,
[L_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[N7_2_CONSULTANT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[PRE_TREAT_PSA] [real] NULL,
[ROOT_CAUSE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ACTION_ID] [int] NULL,
[ROOT_DECISION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[TreatmentIntent] [int] NULL,
[OtherTreatmentIntent] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[TertiaryReferralKey] [uniqueidentifier] NULL,
[ROOT_PRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_SUBPRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
