CREATE TABLE [Merge_R_Compare].[dbo_tblMAIN_TELETHERAPY]
(
[DW_tblMAIN_TELETHERAPY_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[TELE_ID] [int] NULL,
[CARE_ID] [int] NULL,
[TEMP_ID] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[N10_1_SITE_CODE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_SITE_CODE_DTT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N10_2_CONSULTANT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[N10_3_DECISION_DATE] [smalldatetime] NULL,
[N10_6_TREATMENT_INTENT] [int] NULL,
[N10_7_TREATMENT_SITE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N10_8_START_DATE] [smalldatetime] NULL,
[N10_9_END_DATE] [smalldatetime] NULL,
[N10_10_DOSE] [real] NULL,
[N10_11_FRACTIONS] [real] NULL,
[N10_12_DURATION] [int] NULL,
[N10_13_ACTUAL_DOSE] [real] NULL,
[N10_14_ACTUAL_FRACTIONS] [real] NULL,
[N10_15_ACTUAL_DURATION] [int] NULL,
[N10_16_BEAM_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N10_17_BEAM_ENERGY_1] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N10_17_BEAM_ENERGY_2] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N10_18_FIELDS] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N10_19_COMPLEXITY] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N10_20_ANAESTHETIC] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N10_21_MULTIPLE_PLANNING] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_L26_RT_GIVEN] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_EVENT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_SETTING] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_PRIORITY] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N_CHEMORADIO] [int] NULL,
[L_DOSE_FRACTIONS] [real] NULL,
[L_FRACTIONS_WEEK] [int] NULL,
[L_NAMED_COMP] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_COMP_3MTH] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_SHORT_LONG] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[L_TRIAL] [int] NULL,
[L_FRAME] [int] NULL,
[R_TREAT_TO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DEFINITIVE_TREATMENT] [int] NULL,
[CWT_PROFORMA] [int] NULL,
[L_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[BRAIN_RADIOSURGERY_INDICATOR] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PRE_TREAT_PSA] [real] NULL,
[ROOT_START_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_END_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ACTION_ID] [int] NULL,
[DISCHARGE_SIX_DAYS] [bit] NULL,
[DATE_LAST_FRACTION] [date] NULL,
[PLANNED_START_DATE] [date] NULL,
[DISCHARGE_DATE] [smalldatetime] NULL,
[DISCHARGE_DELAY_REASON] [int] NULL,
[DISCHARGE_DESTINATION] [char] (2) COLLATE Latin1_General_CI_AS NULL,
[PLANNED_REASON] [int] NULL,
[DELAY_REASON] [int] NULL,
[TECHNIQUE] [int] NULL,
[ToxicitySymptom] [int] NULL,
[ROOT_DECISION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[AdjunctiveTherapyID] [int] NULL,
[OtherTreatmentIntent] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HCCEmbolisation] [int] NULL,
[HCCEmbolisationModality] [int] NULL,
[TreatmentCompletedAsPlanned] [int] NULL,
[NotCompleteReasonID] [int] NULL,
[TertiaryReferralKey] [uniqueidentifier] NULL,
[ROOT_PRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_SUBPRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
