CREATE TABLE [Merge_R_Compare].[dbo_AspNetUsers]
(
[DW_AspNetUsers_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[Id] [int] NULL,
[OldId] [uniqueidentifier] NULL,
[UserName] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[Email] [nvarchar] (256) COLLATE Latin1_General_CI_AS NULL,
[EmailConfirmed] [bit] NULL,
[PasswordHash] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SecurityStamp] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PhoneNumber] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PhoneNumberConfirmed] [bit] NULL,
[TwoFactorEnabled] [bit] NULL,
[LockoutEndDateUtc] [datetime] NULL,
[LockoutEnabled] [bit] NULL,
[AccessFailedCount] [int] NULL,
[IsApproved] [bit] NULL,
[CreatedDate] [datetime] NULL,
[LastLoginDate] [datetime] NULL,
[LastPasswordChangeDate] [datetime] NULL,
[OrganisationCode] [nvarchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DepartmentID] [int] NULL,
[FullName] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PasswordReset] [bit] NULL,
[AdminUserID] [int] NULL,
[AssociatedCNSId] [int] NULL,
[LastLockoutDate] [datetime] NULL
) ON [PRIMARY]
GO
