CREATE TABLE [Merge_R_Compare].[dbo_tblMAIN_BRACHYTHERAPY]
(
[DW_tblMAIN_BRACHYTHERAPY_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[BRACHY_ID] [int] NULL,
[CARE_ID] [int] NULL,
[TEMP_ID] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[N11_1_SITE_CODE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_SITE_CODE_DTT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N11_2_CONSULTANT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[N11_3_DECISION_DATE] [smalldatetime] NULL,
[N11_6_TREATMENT_INTENT] [int] NULL,
[N11_7_TYPE] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N11_8_TREATMENT_SITE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N11_9_START_DATE] [smalldatetime] NULL,
[N11_10_END_DATE] [smalldatetime] NULL,
[N11_11_DOSE] [real] NULL,
[N11_12_DURATION] [int] NULL,
[N11_13_FRACTIONS] [real] NULL,
[N11_14_ACTUAL_DOSE] [real] NULL,
[N11_15_DOSE_RATE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N11_16_ACTUAL_DURATION] [int] NULL,
[L_TYPE_OF_DOSE] [int] NULL,
[N11_17_ISOTOPE_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N11_18_ANAESTHETIC] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N11_19_UNSEALED] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N11_20_DELIVERY_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N11_22_STATUS] [int] NULL,
[N_TREATMENT_EVENT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_SETTING] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[L_NAMED_COMP] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_COMP_3MTH] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_SHORT_LONG] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[R_INSERTIONS] [int] NULL,
[R_DOSE_INSERTION] [real] NULL,
[R_TREAT_TO] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[L_TRIAL] [int] NULL,
[ENDOSCOPIC] [bit] NULL,
[DEFINITIVE_TREATMENT] [int] NULL,
[CWT_PROFORMA] [int] NULL,
[L_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[PRE_TREAT_PSA] [real] NULL,
[ROOT_START_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_END_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ACTION_ID] [int] NULL,
[ROOT_DECISION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[AdjunctiveTherapyID] [int] NULL,
[OtherTreatmentIntent] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HCCEmbolisation] [int] NULL,
[HCCEmbolisationModality] [int] NULL,
[NotCompleteReasonID] [int] NULL,
[TreatmentCompletedAsPlanned] [int] NULL,
[TertiaryReferralKey] [uniqueidentifier] NULL,
[ROOT_PRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_SUBPRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
