CREATE TABLE [Merge_R_Compare].[dbo_tblMAIN_SURGERY]
(
[DW_tblMAIN_SURGERY_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[SURGERY_ID] [int] NULL,
[CARE_ID] [int] NULL,
[TEMP_ID] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[N7_1_SITE_CODE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_SITE_CODE_DTT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N7_2_CONSULTANT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[N7_3_SPECIALTY] [int] NULL,
[N7_4_TREATMENT_INTENT] [int] NULL,
[N7_5_DECISION_DATE] [smalldatetime] NULL,
[N7_8_ADMISSION_DATE] [smalldatetime] NULL,
[N7_9_SURGERY_DATE] [smalldatetime] NULL,
[L_PROCEDURE_SITE] [int] NULL,
[L_PROCEDURE_TYPE] [int] NULL,
[L_PROCEDURE] [int] NULL,
[L_PROCEDURE_SITE2] [int] NULL,
[L_PROCEDURE_TYPE2] [int] NULL,
[L_PROCEDURE2] [int] NULL,
[L_PROCEDURE_SITE3] [int] NULL,
[L_PROCEDURE_TYPE3] [int] NULL,
[L_PROCEDURE3] [int] NULL,
[L_PROCEDURE_SITE4] [int] NULL,
[L_PROCEDURE_TYPE4] [int] NULL,
[L_PROCEDURE4] [int] NULL,
[N7_10_PROCEDURE_1] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N7_11_PROCEDURE_2] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N7_11_PROCEDURE_3] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N7_11_PROCEDURE_4] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N7_12_DISCHARGE_DATE] [smalldatetime] NULL,
[N7_13_DISCHARGE_DESTINATION] [int] NULL,
[N_TREATMENT_EVENT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_SETTING] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[L_TRIAL] [int] NULL,
[L_SURGEON] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[L_SURGEON_NAME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_GRADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ASSISTANT_1] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[L_ASSISTANT_NAME_1] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_GRADE_1] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ASSISTANT_2] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[L_ASSISTANT_NAME_2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_GRADE_2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ANAESTHETIST_NAME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ANAESTHETIST] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ANAESTHETIST_NAME_2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ANAESTHETIST_2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_URGENCY] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_ANASTOMOSIS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_BLOOD_LOSS] [real] NULL,
[L_SUPPORT] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_COMPLICATIONS] [int] NULL,
[L_COMPLICATIONS2] [int] NULL,
[L_COMPLICATIONS3] [int] NULL,
[L_OTHER_COMP] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[L_POST_COMP] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[L_TRANSFER] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[L_DAYS] [int] NULL,
[L_RETURN_ITU] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_REASON_RETURN] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[L_DAYS_BACK] [int] NULL,
[DEFINITIVE_TREATMENT] [int] NULL,
[CWT_PROFORMA] [int] NULL,
[L_DISCHARGE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[STEM_CELL_INFUSION_SOURCE_ID] [int] NULL,
[STEM_CELL_INFUSION_SOURCE_ID2] [int] NULL,
[STEM_CELL_INFUSION_SOURCE_ID3] [int] NULL,
[STEM_CELL_INFUSION_DONOR_ID] [int] NULL,
[STEM_CELL_INFUSION_DONOR_ID2] [int] NULL,
[STEM_CELL_INFUSION_DONOR_ID3] [int] NULL,
[SURGEON_3] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[SURGEON_3_GRADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SURGEON_3_NAME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SURGEON_4] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[SURGEON_4_GRADE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[SURGEON_4_NAME] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ROOT_ADMISSION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_PERFORMED_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE1] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE2] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE3] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE4] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE5] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[GMC_CODE6] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[PLANNED_ITU_ADMISSION] [int] NULL,
[ACTION_ID] [int] NULL,
[PLANNED_PROCEDURE_DATE] [datetime] NULL,
[DATE_DISCREPANCY_REASON] [int] NULL,
[ROOT_DECISION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[SurgicalAccessID] [int] NULL,
[CCLGGuidelineName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TreatedToCCLGGuidelines] [int] NULL,
[ConditioningRegimenPrimary] [int] NULL,
[ConditioningRegimenSub1] [int] NULL,
[ConditioningRegimenSub2] [int] NULL,
[ResectionStatus] [int] NULL,
[ASAGrade] [int] NULL,
[AdjunctiveTherapyID] [int] NULL,
[OtherTreatmentIntent] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[TherapyType] [int] NULL,
[SNOMEDProcedure] [int] NULL,
[SNOMEDProcedure2] [int] NULL,
[SNOMEDProcedure3] [int] NULL,
[TertiaryReferralKey] [uniqueidentifier] NULL,
[StartTime] [char] (5) COLLATE Latin1_General_CI_AS NULL,
[EndTime] [char] (5) COLLATE Latin1_General_CI_AS NULL,
[RegionalAnaestheticTechnique] [int] NULL,
[SNOMEDRTT] [int] NULL,
[SNOMEDProcedure4] [int] NULL,
[ROOT_PRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_SUBPRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
