CREATE TABLE [Merge_R_Compare].[dbo_tblTRACKING_COMMENTS]
(
[DW_tblTRACKING_COMMENTS_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[COM_ID] [int] NULL,
[CARE_ID] [int] NULL,
[USER_ID] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DATE_TIME] [datetime] NULL,
[COMMENTS] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ROOT_CAUSE_TRACKING_NOTES_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
