CREATE TABLE [Merge_R_Compare].[dbo_tblMAIN_CHEMOTHERAPY]
(
[DW_tblMAIN_CHEMOTHERAPY_ID] [bigint] NOT NULL IDENTITY(1, 1),
[DW_LOAD_ID] [int] NULL,
[DW_CREATION_DATE_TIME] [datetime] NULL,
[DW_MODIFIED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_ID] [int] NULL,
[DW_SOURCE_PATIENT_ID] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[DW_SOURCE_SYSTEM_CREATED_DATE_TIME] [datetime] NULL,
[DW_SOURCE_SYSTEM_MODIFIED_DATE_TIME] [datetime] NULL,
[CHEMO_ID] [int] NULL,
[CARE_ID] [int] NULL,
[TEMP_ID] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PROG_NUMBER] [int] NULL,
[REG_NUMBER] [int] NULL,
[N9_1_SITE_CODE] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N_SITE_CODE_DTT] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N9_2_CONSULTANT] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[N9_3_SPECIALTY] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[N9_4_DECISION_DATE] [smalldatetime] NULL,
[N9_7_THERAPY_TYPE] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[N9_8_TREATMENT_INTENT] [int] NULL,
[N9_9_DRUG_REGIMEN] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[N9_10_START_DATE] [smalldatetime] NULL,
[N9_16_CYCLE_NO] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[N9_20_DOSAGE] [int] NULL,
[N9_21_DURATION] [int] NULL,
[N9_22_RESPONSE] [int] NULL,
[N9_24_CHEMO_HRG] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[N_B7_ENDOCRINE_TYPE] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[N_L27_CHEMO_GIVEN] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_EVENT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_TREATMENT_SETTING] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[N_CHEMORADIO] [int] NULL,
[L_END_DATE] [smalldatetime] NULL,
[L_TRIAL] [int] NULL,
[L_CYCLE_GIVEN] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[DEPRECATED_20_02_L_NAMED_COMP] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[L_AROMATASE] [int] NULL,
[L_AROMATASE_DETAILS] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[L_ROUTE] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DEFINITIVE_TREATMENT] [int] NULL,
[CWT_PROFORMA] [int] NULL,
[L_HEIGHT] [real] NULL,
[L_WEIGHT] [real] NULL,
[L_WHO_STATUS] [int] NULL,
[L_CO_MORBIDITY] [int] NULL,
[L_DOSE_REDUCTION] [int] NULL,
[L_TIME_DELAY] [int] NULL,
[L_STOPPED_EARLY] [int] NULL,
[L_DATE_DEATH] [smalldatetime] NULL,
[L_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[CONSULTANT_AGE_SPECIALTY] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[TRANS_ARTERIAL_CHEMOEMBO] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[ROOT_START_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_END_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ACTION_ID] [int] NULL,
[CHEMO_TIMING] [int] NULL,
[DEPRECATED_20_02_DISCHARGE_DATE] [smalldatetime] NULL,
[DEPRECATED_20_02_DISCHARGE_DELAY_REASON] [int] NULL,
[DEPRECATED_20_02_DISCHARGE_DESTINATION] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DISCHARGE_SUMMARY_SENT] [int] NULL,
[HANADrugRegimen] [int] NULL,
[AcuteToxicity] [int] NULL,
[ROOT_DECISION_DATE_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[PrimaryInductionFailureID] [int] NULL,
[AdjunctiveTherapyID] [int] NULL,
[OtherTreatmentIntent] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HCCEmbolisation] [int] NULL,
[HCCEmbolisationModality] [int] NULL,
[TreatmentCompletedAsPlanned] [int] NULL,
[NotCompleteReasonID] [int] NULL,
[PalExtendLifeExpectancy] [bit] NULL,
[PalRelieveControlSymptoms] [bit] NULL,
[PalAchieveRemission] [bit] NULL,
[PalDelayTumourProgression] [bit] NULL,
[OtherReasonNotCompleted] [varchar] (55) COLLATE Latin1_General_CI_AS NULL,
[RegOutcomeToxicity] [int] NULL,
[RegOutcomeNonCurative] [int] NULL,
[TertiaryReferralKey] [uniqueidentifier] NULL,
[ROOT_PRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL,
[ROOT_SUBPRIM_ADJUSTMENT_COMMENTS] [text] COLLATE Latin1_General_CI_AS NULL
) ON [PRIMARY]
GO
