CREATE TABLE [Merge_R_Compare].[pre_scr_referrals]
(
[OrigCARE_ID] [int] NOT NULL,
[CARE_ID] [int] NULL,
[OrigSrcSysID] [tinyint] NOT NULL,
[SrcSysID] [int] NOT NULL,
[SrcSysCode] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[SrcSysName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PatientPathwayID] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[PatientPathwayIdIssuer] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[PATIENT_ID] [int] NULL,
[MainRefActionId] [int] NULL,
[DiagnosisActionId] [int] NULL,
[DemographicsActionId] [int] NULL,
[Forename] [nvarchar] (141) COLLATE Latin1_General_CI_AS NULL,
[Surname] [nvarchar] (60) COLLATE Latin1_General_CI_AS NULL,
[DateBirth] [datetime] NULL,
[HospitalNumber] [nvarchar] (30) COLLATE Latin1_General_CI_AS NULL,
[NHSNumber] [nvarchar] (4000) COLLATE Latin1_General_CI_AS NULL,
[NHSNumberStatusCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[NstsStatus] [int] NULL,
[IsTemporaryNHSNumber] [int] NOT NULL,
[DeathStatus] [int] NULL,
[DateDeath] [date] NULL,
[PctCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PctDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CcgCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[CcgDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CancerSite] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSubSiteCode] [int] NULL,
[CancerSubSiteDesc] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[CancerTypeDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PriorityTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PriorityTypeDesc] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[SourceReferralCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[SourceReferralDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ReferralMethodCode] [int] NULL,
[DecisionToReferDate] [smalldatetime] NULL,
[TumourStatusCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[TumourStatusDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCodeCwt] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusDescCwt] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ConsultantCode] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[ConsultantName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[InappropriateRef] [int] NULL,
[TransferReason] [int] NULL,
[TransferNewRefDate] [smalldatetime] NULL,
[TransferTumourSiteCode] [int] NULL,
[TransferTumourSiteDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TransferActionedDate] [smalldatetime] NULL,
[TransferSourceCareId] [int] NULL,
[TransferOrigSourceCareId] [int] NULL,
[FastDiagInformedDate] [smalldatetime] NULL,
[FastDiagExclDate] [datetime] NULL,
[FastDiagCancerSiteID] [int] NULL,
[FastDiagCancerSiteOverrideID] [int] NULL,
[FastDiagCancerSiteCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCancerSiteDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FastDiagEndReasonID] [int] NULL,
[FastDiagEndReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagEndReasonDesc] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonID] [int] NULL,
[FastDiagDelayReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonDesc] [varchar] (160) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonComments] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[FastDiagExclReasonID] [int] NULL,
[FastDiagExclReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagExclReasonDesc] [varchar] (80) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOrgID] [int] NULL,
[FastDiagOrgCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOrgDesc] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCommMethodID] [int] NULL,
[FastDiagCommMethodCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCommMethodDesc] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOtherCommMethod] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FastDiagInformingCareProfID] [int] NULL,
[FastDiagInformingCareProfCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[FastDiagInformingCareProfDesc] [varchar] (70) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOtherCareProf] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FDPlannedInterval] [bit] NULL,
[DateDiagnosis] [smalldatetime] NULL,
[DateNoCancer] [smalldatetime] NULL,
[AgeAtDiagnosis] [int] NULL,
[DiagnosisCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisSubCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisSubDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[OrgIdDiagnosis] [int] NULL,
[OrgCodeDiagnosis] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescDiagnosis] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[SnomedCT_ID] [int] NULL,
[SnomedCT_MCode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[SnomedCT_ConceptID] [bigint] NULL,
[SnomedCT_Desc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Histology] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[DateReceipt] [smalldatetime] NULL,
[AgeAtReferral] [int] NULL,
[AppointmentCancelledDate] [smalldatetime] NULL,
[DateConsultantUpgrade] [smalldatetime] NULL,
[DateFirstSeen] [smalldatetime] NULL,
[OrgIdUpgrade] [int] NULL,
[OrgCodeUpgrade] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescUpgrade] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[OrgIdFirstSeen] [int] NULL,
[OrgCodeFirstSeen] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescFirstSeen] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[OrgCodeMainCurrent] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescMainCurrent] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[FirstAppointmentTypeCode] [int] NULL,
[FirstAppointmentTypeDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstAppointmentOffered] [int] NULL,
[ReasonNoAppointmentCode] [int] NULL,
[ReasonNoAppointmentDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenAdjTime] [int] NULL,
[FirstSeenAdjReasonCode] [int] NULL,
[FirstSeenAdjReasonDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenDelayReasonCode] [int] NULL,
[FirstSeenDelayReasonDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenDelayReasonComment] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[DTTAdjTime] [int] NULL,
[DTTAdjReasonCode] [int] NULL,
[DTTAdjReasonDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[IsBCC] [int] NULL,
[IsCwtCancerDiagnosis] [int] NULL,
[UnderCancerCareFlag] [int] NULL,
[RefreshMaxActionDate] [datetime] NULL,
[ReportDate] [datetime] NULL,
[DateLastTracked] [datetime] NULL,
[DaysSinceLastTracked] [int] NULL,
[RTTBreachStatus] [int] NULL,
[DelayReasonCode] [int] NULL,
[DelayReasonDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[DelayReasonComment] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[SharedBreach] [decimal] (2, 1) NULL,
[PredictedBreachYear] [int] NULL,
[PredictedBreachMonth] [int] NULL,
[LateralityCode] [varchar] (1) COLLATE Latin1_General_CI_AS NULL,
[LateralityDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ClinicalTStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[ClinicalNStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[ClinicalMStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[ClinicalTNM_Group] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PathologicalTStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PathologicalNStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PathologicalMStage] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PathologicalTNM_Group] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FIGO_Stage1] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[FIGO_Stage2] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[FIGO_Stage3] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[RISS_Stage] [int] NULL,
[AnnArborStageCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[AnnArborStageDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[BinetStageCode] [int] NULL,
[BinetStageDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CNSIndicatorCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[MaxWHO_Status] [int] NULL,
[IsCOSD_Staging] [smallint] NULL,
[IsCOSD_StagingComplete] [bit] NULL,
[IsCOSD_PerformanceStatus] [smallint] NULL,
[IsCOSD_PerformanceStatusComplete] [bit] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_care_id] ON [Merge_R_Compare].[pre_scr_referrals] ([SrcSysID], [CARE_ID]) ON [PRIMARY]
GO
